# This is the configuration file for kitty terminal
# For more information, see https://sw.kovidgoyal.net/kitty/conf.html
# For your custom configurations, put it in ./kitty.conf
font_family Liberation
bold_font auto
italic_font auto
bold_italic_font auto
enable_audio_bell no
font_size 14.0
window_padding_width 21.75
confirm_os_window_close 0
cursor_trail 2
cursor_shape block

# Copy
map ctrl+c    copy_or_interrupt

# Themes can override any settings in this file
background_opacity 0.9
#hide_window_decorations yes
#confirm_os_window_close 0
#
#
# Search
map ctrl+f   launch --location=hsplit --allow-remote-control kitty +kitten search.py @active-kitty-window-id
map kitty_mod+f   launch --location=hsplit --allow-remote-control kitty +kitten search.py @active-kitty-window-id

# Scroll & Zoom
map page_up    scroll_page_up
map page_down    scroll_page_down

map ctrl+plus  change_font_size all +1
map ctrl+equal  change_font_size all +1
map ctrl+kp_add  change_font_size all +1
map ctrl+minus       change_font_size all -1
map ctrl+underscore       change_font_size all -1
map ctrl+kp_subtract       change_font_size all -1
map ctrl+0 change_font_size all 0
map ctrl+kp_0 change_font_size all 0
